repos:
  - repo: local
    hooks:
      - id: swiftformat
        name: SwiftFormat
        entry: swiftformat
        language: system
        pass_filenames: false     # ルートで一括実行
        args: ["--swiftversion", "5.10", "."]
        files: \.swift$           # Swiftファイルがあるときだけ動く
      - id: swiftlint
        name: SwiftLint
        entry: swiftlint
        language: system
        pass_filenames: false
        args: ["--strict"]
        files: \.swift$
