repos:
  - repo: local
    hooks:
      - id: swiftformat
        name: swiftformat
        entry: swiftformat
        language: system
        types: [swift]
        args: ["--swiftversion", "5.10", "."]
      - id: swiftlint
        name: swiftlint
        entry: swiftlint
        language: system
        types: [swift]
        pass_filenames: false   # ルートで一括Lint
        args: ["--strict"]
