repos:
  - repo: local
    hooks:
      - id: swiftformat
        name: swiftformat
        entry: swiftformat
        language: system
        types: [swift]
        pass_filenames: false # ← 追加
        args: ["--swiftversion", "5.10", "."] # ルートを対象
      - id: swiftlint
        name: swiftlint
        entry: swiftlint
        language: system
        types: [swift]
        pass_filenames: false
        args: ["--strict"]
