# SwiftLint configuration for CI autofix-first workflow

disabled_rules:
  - multiple_closures_with_trailing_closure
  - large_tuple
  - identifier_name           # 'to' などは自動修正不可のため一旦OFF
  - superfluous_disable_command

type_body_length:
  warning: 350
  error: 450

