name: SynapseTasks
options:
  deploymentTarget: { iOS: "17.0" }
  createIntermediateGroups: true
targets:
  SynapseTasks:
    type: application
    platform: iOS
    sources: [Sources/App]
    settings:
      base:
        INFOPLIST_FILE: Sources/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.kousuke.synapsetasks
        BASE_CONFIGURATION_REFERENCE: Configs/Base.xcconfig

  SynapseTasksTests:
    type: bundle.unit-test
    platform: iOS
    sources: [Sources/Tests]
    dependencies: [{ target: SynapseTasks }]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.kousuke.synapsetasks.tests
        CODE_SIGNING_ALLOWED: NO

schemes:
  SynapseTasks:
    build: { targets: { SynapseTasks: all } }
    test:  { targets: [SynapseTasksTests] }
    run:   { config: Debug }
