name: iOS CI (self-heal)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-lint-capture:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          xcodebuild -version
          xcodebuild -showsdks

      - name: Install tools (SwiftFormat, xcpretty)
        run: |
          brew update
          brew install swiftformat@0.53 || true
          brew link --overwrite swiftformat@0.53
          gem install xcpretty --no-document
          swiftformat --version

      - name: Ensure Info.plist has versions
        run: |
          chmod +x scripts/ensure_plist.sh
          ./scripts/ensure_plist.sh "SynapseTasks" "1.0" "$GITHUB_RUN_NUMBER"

      # ======= Autofix → Lint の順 =======
      - name: SwiftFormat autofix
        run: swiftformat .

      - name: Commit autofix (if any)
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "style(ci): swiftformat autofix"
          fi

      - name: SwiftFormat lint
        run: swiftformat --lint .

      - name: iOS Build (simulator)
        run: |
          set -e
          xcodebuild \
            -project SynapseTasks.xcodeproj \
            -scheme SynapseTasks \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=18.2" \
            build | xcpretty

      - name: UI capture (multi-shots)
        run: |
          chmod +x scripts/ui_capture.sh
          SCHEME=SynapseTasks \
          PROJECT=SynapseTasks.xcodeproj \
          RUNTIME=com.apple.CoreSimulator.SimRuntime.iOS-18-2 \
          DEVTYPE=com.apple.CoreSimulator.SimDeviceType.iPhone-15 \
          ./scripts/ui_capture.sh

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: artifacts/screenshots/*.png

      # 失敗時の自己修復フロー（オプション）
      - name: On failure - open PR with fixes
        if: failure()
        run: |
          git switch -c ci/self-heal || git checkout -b ci/self-heal
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to propose."
            exit 0
          fi
          git commit -m "ci(self-heal): auto-fixes from failed run"
          git push -u origin ci/self-heal || true
          echo "::notice::If push blocked, please open PR from ci/self-heal."
