name: iOS CI (self-heal)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  ios:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Select Xcode 16.2
        run: |
          sudo xcode-select -s /Applications/Xcode_16.2.app/Contents/Developer
          xcodebuild -version

      - name: Install tools
        run: |
          brew update
          brew install swiftformat
          gem install xcpretty --no-document
          swiftformat --version

      # ====== 先に整形 → 自動コミット → それから lint ======
      - name: SwiftFormat autofix
        run: swiftformat .

      - name: Commit autofix (if any)
        run: |
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "ci(self-heal): swiftformat autofix"
            git push || true
          fi

      - name: SwiftFormat lint
        run: swiftformat --lint .

      - name: Build (Simulator)
        run: |
          set -e
          xcodebuild \
            -project SynapseTasks.xcodeproj \
            -scheme SynapseTasks \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=18.2" \
            build | xcpretty

      - name: UI capture (multi shots)
        run: |
          chmod +x scripts/ui_capture.sh
          SCHEME=SynapseTasks \
          PROJECT=SynapseTasks.xcodeproj \
          RUNTIME=com.apple.CoreSimulator.SimRuntime.iOS-18-2 \
          DEVTYPE=com.apple.CoreSimulator.SimDeviceType.iPhone-15 \
          ./scripts/ui_capture.sh

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: artifacts/screenshots/*.png

