name: iOS CI
on: [push, pull_request]
jobs:
  lint:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: brew install xcodegen swiftformat swiftlint
      - run: pip3 install --user pre-commit
      - run: xcodegen generate
      - name: pre-commit (swiftformat & swiftlint)
        run: ~/.local/bin/pre-commit run --all-files

  build-test:
    runs-on: macos-14
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - run: brew install xcodegen
      - run: xcodegen generate
      - name: Build & Test (iPhone 17)
        run: |
          DEV=$(xcrun simctl list devices | awk -F '[()]' '/iPhone 17/ {print $2; exit}')
          xcodebuild -scheme SynapseTasks -destination "platform=iOS Simulator,OS=latest,id=$DEV" -configuration Debug test
