name: iOS CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16.x
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.x'

      - name: Build (Simulator)
        env:
          PROJECT: SynapseTasks.xcodeproj
          SCHEME: SynapseTasks
          DESTINATION: ""
        run: |
          xcodebuild -list -project "$PROJECT"
          # DESTINATION は scripts と同じロジックで自動解決できるようにするなら scripts を使う手もあり
          xcodebuild \
            -project "$PROJECT" \
            -scheme "$SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            -configuration Debug \
            build


