name: lint

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode 16.x
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.x'

      - name: Install tools
        run: |
          brew update
          brew install swiftformat swiftlint

      - name: SwiftFormat (lint mode)
        run: swiftformat --lint .

      - name: SwiftLint (no fix)
        run: swiftlint

