name: UI Capture

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  ui-capture:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Preflight (verify repo state)
        run: |
          set -x
          git rev-parse --short HEAD
          git log -1 --oneline
          ls -la
          ls -la scripts || true
          echo "---- head of scripts/ui_capture.sh ----"
          head -n 40 scripts/ui_capture.sh || true

      - name: Build & Capture Screens
        env:
          PROJECT: SynapseTasks.xcodeproj
          SCHEME: SynapseTasks
        run: |
          chmod +x scripts/ui_capture.sh
          ./scripts/ui_capture.sh

